version: '3.8'

services:
  web:
    build: ./testing
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./testing/:/usr/src/testing/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=mydb

volumes:
  postgres_data: