# Generated by Django 4.0.8 on 2022-10-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
